import { DEFAULT_SSAO_OPTIONS, DEFAULT_VOLUMETRIC_OPTIONS } from "../../pipeline/types";
import type { SoftwareRasterMode } from "./types";
import {
	DEFAULT_GAMMA,
	FXAA_EDGE_THRESHOLD_MIN,
	FXAA_EDGE_THRESHOLD_MULTIPLIER,
	FXAA_QUALITY,
	FXAA_SUBPIX_QUALITY,
	MAX_EXPOSURE,
	MAX_GAMMA,
	MIN_GAMMA,
	POST_PROCESS_NOISE_REFERENCE_WIDTH,
	VOLUMETRIC_SIGMA_T_SCALE,
} from "../constants";

/**
 * Software backend post-processing constants.
 */
export const PostProcessConstants = Object.freeze({
	FXAA_EDGE_THRESHOLD_MIN,
	FXAA_EDGE_THRESHOLD_MULTIPLIER,
	FXAA_SUBPIX_QUALITY,
	FXAA_ITERATIONS: 12,
	FXAA_QUALITY,
	NOISE_REFERENCE_WIDTH: POST_PROCESS_NOISE_REFERENCE_WIDTH,
	MIN_GAMMA,
	MAX_GAMMA,
	DEFAULT_GAMMA,
	MAX_EXPOSURE,
});

export const VolumetricConstants = Object.freeze({
	SIGMA_T_SCALE: VOLUMETRIC_SIGMA_T_SCALE,
	MIN_RAY_DISTANCE: 0.1,
	MIN_RAY_DIR_Z: 1e-6,
	MIN_ADAPTIVE_SAMPLE_COUNT: 8,
	MIN_DOWN_SAMPLE: 1,
	MAX_DOWN_SAMPLE: 8,
	MIN_SAMPLES: 1,
	MAX_SAMPLES: 256,
	DEFAULT_DOWN_SAMPLE: DEFAULT_VOLUMETRIC_OPTIONS.downsample,
	DEFAULT_SAMPLES: DEFAULT_VOLUMETRIC_OPTIONS.samples,
	MIN_SHADOW_SAMPLE_INTERVAL: 1,
	MAX_SHADOW_SAMPLE_INTERVAL: 32,
	MIN_BILATERAL_DEPTH_SIGMA: 1e-4,
	MAX_WEIGHT: 10,
	DEFAULT_WEIGHT: DEFAULT_VOLUMETRIC_OPTIONS.weight,
	MAX_AIR_DENSITY: 10,
	TRANSMITTANCE_EARLY_EXIT: 0.001,
	GRID_SAMPLE_JITTER_STRENGTH: 0.75,
	SCENE_BOUNDS_FADE_START_MULTIPLIER: 1.05,
	SCENE_BOUNDS_FADE_END_MULTIPLIER: 1.8,
	SCENE_DEPTH_LIMIT_MULTIPLIER: 1.6,
	MIN_SCENE_BOUNDS_RADIUS: 1.0,
	TEMPORAL_ACCUMULATION_FACTOR: 0.95,
});

export const SSAOConstants = Object.freeze({
	DEFAULT_SAMPLES: DEFAULT_SSAO_OPTIONS.samples,
	DEFAULT_RADIUS: DEFAULT_SSAO_OPTIONS.radius,
	DEFAULT_BIAS: DEFAULT_SSAO_OPTIONS.bias,
	DEFAULT_INTENSITY: DEFAULT_SSAO_OPTIONS.intensity,
	NOISE_SIZE: 4,
});

export const DEFAULT_SOFTWARE_RASTER_MODE: SoftwareRasterMode = "scanline";
export const DEFAULT_SOFTWARE_TILE_SIZE = 32;

export const CoreConstants = Object.freeze({
	EPSILON: 1e-6,
	OPAQUE_ALPHA: 255,
	WIREFRAME_DEPTH_BIAS: 0.1,
	MAX_CHANNEL_VALUE: 255,
});

export const RenderConstants = Object.freeze({
	REFLECTION_BUFFER_ALPHA: 255,
	REFLECTION_TRANSPARENT_THRESHOLD: 0.99,
});
