import { PARTICLE_QUAD_VERTICES } from "../constants";
import { TextureFormat } from "../types";
import { getWebGPURenderTargetPixelByteCost } from "./WebGPUTextureFormatInfo";

export type WebGPUDeferredGBufferLayout = "base" | "extended";

export const WEBGPU_SHADOW_ATLAS_COLUMNS = 4;
export const WEBGPU_SHADOW_ATLAS_ROWS = 3;
export const WEBGPU_SH_COEFFICIENT_COUNT = 16;
export const WEBGPU_TEXTURE_SLOT_COUNT = 16;
// Three frame samplers plus these material samplers must fit WebGPU's default
// maxSamplersPerShaderStage limit of 16.
export const WEBGPU_TEXTURE_DEDICATED_SAMPLER_SLOT_COUNT = 13;
export const WEBGPU_SCENE_FRAME_FRAGMENT_TEXTURE_COUNT = 8;
export const WEBGPU_SCENE_FRAME_FRAGMENT_SAMPLER_COUNT = 3;
export const WEBGPU_GBUFFER_READ_TEXTURE_COUNT = 9;
export const WEBGPU_SCENE_REQUIRED_FRAGMENT_SAMPLED_TEXTURE_COUNT =
	WEBGPU_SCENE_FRAME_FRAGMENT_TEXTURE_COUNT + WEBGPU_TEXTURE_SLOT_COUNT + 1;
export const WEBGPU_DEFERRED_REQUIRED_FRAGMENT_SAMPLED_TEXTURE_COUNT =
	WEBGPU_SCENE_FRAME_FRAGMENT_TEXTURE_COUNT +
	WEBGPU_GBUFFER_READ_TEXTURE_COUNT;
export const WEBGPU_PLANAR_REFLECTION_REQUIRED_FRAGMENT_SAMPLED_TEXTURE_COUNT =
	WEBGPU_SCENE_REQUIRED_FRAGMENT_SAMPLED_TEXTURE_COUNT + 1;
export const WEBGPU_DECAL_REQUIRED_FRAGMENT_SAMPLED_TEXTURE_COUNT =
	WEBGPU_GBUFFER_READ_TEXTURE_COUNT + WEBGPU_TEXTURE_SLOT_COUNT + 1;
export const WEBGPU_REQUIRED_FRAGMENT_SAMPLED_TEXTURE_COUNT = Math.max(
	WEBGPU_SCENE_REQUIRED_FRAGMENT_SAMPLED_TEXTURE_COUNT,
	WEBGPU_DEFERRED_REQUIRED_FRAGMENT_SAMPLED_TEXTURE_COUNT,
	WEBGPU_PLANAR_REFLECTION_REQUIRED_FRAGMENT_SAMPLED_TEXTURE_COUNT,
	WEBGPU_DECAL_REQUIRED_FRAGMENT_SAMPLED_TEXTURE_COUNT
);
export const WEBGPU_SCENE_REQUIRED_FRAGMENT_SAMPLER_COUNT =
	WEBGPU_SCENE_FRAME_FRAGMENT_SAMPLER_COUNT +
	WEBGPU_TEXTURE_DEDICATED_SAMPLER_SLOT_COUNT;
export const WEBGPU_REQUIRED_FRAGMENT_STORAGE_BUFFER_COUNT = 8;
export const WEBGPU_FRAME_CAMERA_UNIFORM_FLOATS = 72;
export const WEBGPU_FRAME_LIGHT_UNIFORM_FLOATS = 420;
export const WEBGPU_FRAME_SHADOW_UNIFORM_FLOATS = 1440;
export const WEBGPU_FRAME_ENVIRONMENT_UNIFORM_FLOATS = 1052;
export const WEBGPU_MODEL_UNIFORM_FLOATS = 244;
export const WEBGPU_FRAME_CAMERA_UNIFORM_BYTE_SIZE =
	WEBGPU_FRAME_CAMERA_UNIFORM_FLOATS * 4;
export const WEBGPU_FRAME_LIGHT_UNIFORM_BYTE_SIZE =
	WEBGPU_FRAME_LIGHT_UNIFORM_FLOATS * 4;
export const WEBGPU_FRAME_SHADOW_UNIFORM_BYTE_SIZE =
	WEBGPU_FRAME_SHADOW_UNIFORM_FLOATS * 4;
export const WEBGPU_FRAME_ENVIRONMENT_UNIFORM_BYTE_SIZE =
	WEBGPU_FRAME_ENVIRONMENT_UNIFORM_FLOATS * 4;
export const WEBGPU_MODEL_UNIFORM_BYTE_SIZE =
	WEBGPU_MODEL_UNIFORM_FLOATS * 4;
export const WEBGPU_MODEL_ANIMATION_UNIFORM_FLOATS = 8;
export const WEBGPU_MRT_COLOR_TARGET_COUNT = 5;
export const WEBGPU_MRT_COLOR_FORMATS = [
	TextureFormat.RGBA16Float,
	TextureFormat.RGBA8Unorm,
	TextureFormat.RGBA8Unorm,
	TextureFormat.RGBA16Float,
	TextureFormat.RGBA16Float,
] as const;
export const WEBGPU_MRT_COLOR_BYTES_PER_SAMPLE =
	WEBGPU_MRT_COLOR_FORMATS.reduce(
		(total, format) =>
			total + getWebGPURenderTargetPixelByteCost(format),
		0
	);
/**
 * Fixed color-attachment order for the WebGPU deferred G-buffer.
 *
 * This order is part of the fragment-output and render-pass ABI.
 */
export enum GBufferSlot {
	AlbedoAlpha = 0,
	NormalRoughMetal = 1,
	EmissiveOcclusion = 2,
	MotionDepth = 3,
	Specular = 4,
	CoatSheen = 5,
	SheenReflectance = 6,
}

export const WEBGPU_DEFERRED_COLOR_TARGET_COUNT =
	GBufferSlot.SheenReflectance + 1;
export const WEBGPU_DEFERRED_COLOR_FORMATS = [
	TextureFormat.RGBA8Unorm,
	TextureFormat.RGBA8Unorm,
	TextureFormat.RGBA16Float,
	TextureFormat.RGBA16Float,
	TextureFormat.RGBA16Float,
	TextureFormat.RGBA16Float,
	TextureFormat.RGBA8Unorm,
] as const;
export const WEBGPU_DEFERRED_COLOR_BYTES_PER_SAMPLE =
	WEBGPU_DEFERRED_COLOR_FORMATS.reduce(
		(total, format) =>
			total + getWebGPURenderTargetPixelByteCost(format),
		0
	);
export const WEBGPU_DEFERRED_BASE_COLOR_TARGET_COUNT = 4;
export const WEBGPU_DEFERRED_BASE_COLOR_BYTES_PER_SAMPLE =
	WEBGPU_DEFERRED_COLOR_FORMATS
		.slice(0, WEBGPU_DEFERRED_BASE_COLOR_TARGET_COUNT)
		.reduce(
			(total, format) =>
				total + getWebGPURenderTargetPixelByteCost(format),
			0
		);
export const WEBGPU_DEFERRED_STORAGE_TEXTURE_COUNT = 2;

export const WEBGPU_DEFERRED_MATERIAL_MODEL_MASK = 0x3;
export const WEBGPU_DEFERRED_MATERIAL_CLEARCOAT_BIT = 1 << 2;
export const WEBGPU_DEFERRED_MATERIAL_SHEEN_BIT = 1 << 3;
export const WEBGPU_DEFERRED_MATERIAL_IRIDESCENCE_BIT = 1 << 4;
export const WEBGPU_DEFERRED_MATERIAL_ANISOTROPY_BIT = 1 << 5;
export const WEBGPU_DEFERRED_MATERIAL_SPECULAR_BIT = 1 << 6;
export const WEBGPU_DEFERRED_MATERIAL_RECEIVE_SHADOWS_BIT = 1 << 7;
export const WEBGPU_DEFERRED_RENDER_LAYER_MASK = 0x7ff;
export const WEBGPU_MAX_MORPH_TARGETS = 8;

export const WEBGPU_SCENE_ATTR_POSITION = 0;
export const WEBGPU_SCENE_ATTR_UV0 = 1;
export const WEBGPU_SCENE_ATTR_NORMAL = 2;
export const WEBGPU_SCENE_ATTR_TANGENT = 3;
export const WEBGPU_SCENE_ATTR_UV1 = 4;
export const WEBGPU_SCENE_ATTR_JOINTS0 = 5;
export const WEBGPU_SCENE_ATTR_WEIGHTS0 = 6;
export const WEBGPU_SCENE_ATTR_JOINTS1 = 7;
export const WEBGPU_SCENE_ATTR_WEIGHTS1 = 8;
export const WEBGPU_SCENE_ATTR_UV2 = 9;
export const WEBGPU_SCENE_ATTR_UV3 = 10;

export const WEBGPU_PARTICLE_BINDING_TEXTURE = 0;
export const WEBGPU_PARTICLE_BINDING_SAMPLER = 1;
export const WEBGPU_PARTICLE_BINDING_UV_TRANSFORM = 2;

export const WEBGPU_PARTICLE_ATTR_QUAD_POSITION = 0;
export const WEBGPU_PARTICLE_ATTR_QUAD_UV = 1;
export const WEBGPU_PARTICLE_ATTR_INSTANCE_POSITION_SIZE = 2;
export const WEBGPU_PARTICLE_ATTR_INSTANCE_COLOR = 3;
export const WEBGPU_PARTICLE_ATTR_INSTANCE_UV_RECT = 4;
export const WEBGPU_PARTICLE_ATTR_INSTANCE_ROTATION = 5;
export const WEBGPU_PARTICLE_ATTR_INSTANCE_RECEIVE_SHADOW = 6;

export const WEBGPU_PARTICLE_QUAD_FLOATS_PER_VERTEX = 4;
export const WEBGPU_PARTICLE_QUAD_VERTEX_STRIDE =
	WEBGPU_PARTICLE_QUAD_FLOATS_PER_VERTEX * 4;
export const WEBGPU_PARTICLE_INSTANCE_FLOATS = 16;
export const WEBGPU_PARTICLE_INSTANCE_STRIDE =
	WEBGPU_PARTICLE_INSTANCE_FLOATS * 4;
export const WEBGPU_PARTICLE_UV_UNIFORM_FLOATS = 8;
export const WEBGPU_PARTICLE_UV_UNIFORM_SIZE =
	WEBGPU_PARTICLE_UV_UNIFORM_FLOATS * 4;
export const WEBGPU_PARTICLE_QUAD_VERTICES = PARTICLE_QUAD_VERTICES;

export const WEBGPU_BINDING_GROUP_CACHE_LIMIT = 4096;
export const WEBGPU_BINDING_GROUP_CACHE_TTL_FRAMES = 3;
export const WEBGPU_PIPELINE_CACHE_LIMIT = 1024;
export const WEBGPU_PIPELINE_LAYOUT_CACHE_LIMIT = 512;
export const WEBGPU_COPY_BATCH_SIZE = 8;
export const WEBGPU_TIMESTAMP_QUERY_CAPACITY = 512;
export const WEBGPU_DEFAULT_SAMPLE_COUNT = 1;
export const WEBGPU_2D_COMPUTE_WORKGROUP_SIZE = 8;

export const WEBGPU_MODEL_BINDING_ANIMATION_PARAMS = 30;
export const WEBGPU_MODEL_BINDING_JOINT_MATRICES = 32;
export const WEBGPU_MODEL_BINDING_MORPH_WEIGHTS = 33;
export const WEBGPU_MODEL_BINDING_MORPH_POSITION =
	WEBGPU_MODEL_BINDING_MORPH_WEIGHTS + 1;
export const WEBGPU_MODEL_BINDING_MORPH_NORMAL =
	WEBGPU_MODEL_BINDING_MORPH_POSITION + 1;
export const WEBGPU_MODEL_BINDING_SHADER_UNIFORMS =
	WEBGPU_MODEL_BINDING_MORPH_NORMAL + 1;
export const WEBGPU_MODEL_BINDING_ANISOTROPY_TEXTURE =
	WEBGPU_MODEL_BINDING_SHADER_UNIFORMS + 1;

export const WEBGPU_CLUSTERED_LIGHT_TYPE_POINT = 0;
export const WEBGPU_CLUSTERED_LIGHT_TYPE_SPOT = 1;
export const WEBGPU_CLUSTERED_LIGHT_TYPE_AREA = 2;

export const WEBGPU_CLUSTERED_SHADER_WORKGROUP_SIZE = 128;
export const WEBGPU_CLUSTERED_PARAMS_FLOATS = 12;
export const WEBGPU_CLUSTERED_HEADER_STRIDE_UINTS = 4;
export const WEBGPU_CLUSTERED_MAX_LIGHTS = 1024;
export const WEBGPU_CLUSTERED_MAX_LIGHTS_PER_CLUSTER = 128;
export const WEBGPU_CLUSTERED_VEC4_STRIDE_FLOATS = 4;
export const WEBGPU_CLUSTERED_AREA_STRIDE_FLOATS = 12;
export const WEBGPU_CLUSTERED_METADATA_STRIDE_UINTS = 2;
export const WEBGPU_CLUSTERED_CULL_STRIDE_FLOATS = 8;

export const WEBGPU_CLUSTERED_LIGHT_FLAG_TYPE_MASK = 0x3;
export const WEBGPU_CLUSTERED_LIGHT_FLAG_CASTS_SHADOW = 1 << 2;
export const WEBGPU_CLUSTERED_LIGHT_FLAG_AFFECTS_VOLUMETRIC = 1 << 3;

export const WEBGPU_CLUSTERED_INDEX_LIGHT_MASK = 0x00ffffff;
export const WEBGPU_CLUSTERED_INDEX_TYPE_SHIFT = 24;
export const WEBGPU_CLUSTERED_INDEX_TYPE_MASK =
	0x3 << WEBGPU_CLUSTERED_INDEX_TYPE_SHIFT;
export const WEBGPU_CLUSTERED_INDEX_SHADOW_BIT = 1 << 26;
export const WEBGPU_CLUSTERED_INDEX_VOLUMETRIC_BIT = 1 << 27;

export const WEBGPU_CLUSTERED_HEADER_FLAG_OVERFLOW = 1 << 0;
export const WEBGPU_CLUSTERED_HEADER_FLAG_HAS_SHADOWED = 1 << 1;
export const WEBGPU_CLUSTERED_HEADER_FLAG_HAS_VOLUMETRIC = 1 << 2;

export const WEBGPU_VOLUMETRIC_LIGHT_STRIDE_FLOATS = 12;

export const WEBGPU_TEXTURE_SLOT = {
	BASE_COLOR: 0,
	METALLIC_ROUGHNESS: 1,
	NORMAL: 2,
	EMISSIVE: 3,
	OCCLUSION: 4,
	SPECULAR: 5,
	SPECULAR_COLOR: 6,
	CLEARCOAT: 7,
	CLEARCOAT_ROUGHNESS: 8,
	CLEARCOAT_NORMAL: 9,
	SHEEN_COLOR: 10,
	SHEEN_ROUGHNESS: 11,
	TRANSMISSION: 12,
	THICKNESS: 13,
	IRIDESCENCE: 14,
	IRIDESCENCE_THICKNESS: 15,
} as const;
