export const WEBGPU_MAX_DIRECTIONAL_LIGHTS = 4;
export const WEBGPU_MAX_POINT_LIGHTS = 4;
export const WEBGPU_MAX_SPOT_LIGHTS = 4;
export const WEBGPU_SH_COEFFICIENT_COUNT = 16;
export const WEBGPU_TEXTURE_SLOT_COUNT = 14;
export const WEBGPU_FRAME_UNIFORM_FLOATS = 472;
export const WEBGPU_MODEL_UNIFORM_FLOATS = 208;
export const WEBGPU_MODEL_ANIMATION_UNIFORM_FLOATS = 4;
export const WEBGPU_MRT_COLOR_TARGET_COUNT = 5;
export const WEBGPU_MRT_COLOR_BYTES_PER_SAMPLE = 40;
export const WEBGPU_MAX_MORPH_TARGETS = 8;
export const WEBGPU_SCENE_VERTEX_FLOATS = 30;
export const WEBGPU_SCENE_VERTEX_STRIDE = WEBGPU_SCENE_VERTEX_FLOATS * 4;

export const WEBGPU_BINDING_GROUP_CACHE_LIMIT = 4096;
export const WEBGPU_BINDING_GROUP_CACHE_TTL_FRAMES = 3;
export const WEBGPU_PIPELINE_CACHE_LIMIT = 1024;
export const WEBGPU_PIPELINE_LAYOUT_CACHE_LIMIT = 512;
export const WEBGPU_COPY_BATCH_SIZE = 8;
export const WEBGPU_TIMESTAMP_QUERY_CAPACITY = 512;
export const WEBGPU_DEFAULT_MSAA_SAMPLE_COUNT = 4;

export const WEBGPU_MODEL_BINDING_ANIMATION_PARAMS = 29;
export const WEBGPU_MODEL_BINDING_JOINT_MATRICES = 30;
export const WEBGPU_MODEL_BINDING_MORPH_WEIGHTS = 31;
export const WEBGPU_MODEL_BINDING_MORPH_POSITION = 32;
export const WEBGPU_MODEL_BINDING_MORPH_NORMAL = 33;

export const WEBGPU_TEXTURE_SLOT = {
	BASE_COLOR: 0,
	METALLIC_ROUGHNESS: 1,
	NORMAL: 2,
	EMISSIVE: 3,
	OCCLUSION: 4,
	SPECULAR: 5,
	SPECULAR_COLOR: 6,
	CLEARCOAT: 7,
	CLEARCOAT_ROUGHNESS: 8,
	CLEARCOAT_NORMAL: 9,
	SHEEN_COLOR: 10,
	SHEEN_ROUGHNESS: 11,
	TRANSMISSION: 12,
	THICKNESS: 13,
} as const;
