export const WEBGPU_MAX_DIRECTIONAL_LIGHTS = 4;
export const WEBGPU_MAX_POINT_LIGHTS = 4;
export const WEBGPU_MAX_SPOT_LIGHTS = 4;
export const WEBGPU_SH_COEFFICIENT_COUNT = 16;
export const WEBGPU_TEXTURE_SLOT_COUNT = 14;
export const WEBGPU_FRAME_UNIFORM_FLOATS = 440;
export const WEBGPU_MODEL_UNIFORM_FLOATS = 208;
export const WEBGPU_MRT_COLOR_TARGET_COUNT = 5;
export const WEBGPU_MRT_COLOR_BYTES_PER_SAMPLE = 40;

export const WEBGPU_TEXTURE_SLOT = {
	BASE_COLOR: 0,
	METALLIC_ROUGHNESS: 1,
	NORMAL: 2,
	EMISSIVE: 3,
	OCCLUSION: 4,
	SPECULAR: 5,
	SPECULAR_COLOR: 6,
	CLEARCOAT: 7,
	CLEARCOAT_ROUGHNESS: 8,
	CLEARCOAT_NORMAL: 9,
	SHEEN_COLOR: 10,
	SHEEN_ROUGHNESS: 11,
	TRANSMISSION: 12,
	THICKNESS: 13,
} as const;
