import type {
	PostProcessPass,
	PostProcessPassRegistrySnapshot,
} from "./PostProcessPass";

export type ResolvedPostProcessState = PostProcessPassRegistrySnapshot;
export type PostProcessCustomPassDescriptor = PostProcessPass;

export {
	PostProcessHistoryManager,
	type PostProcessHistoryPrepareRequest,
} from "./PostProcessHistoryManager";
export {
	PostProcessTransientManager,
	type PostProcessTransientPrepareRequest,
	type PostProcessTransientPrepareResult,
} from "./PostProcessTransientManager";
export {
	DEFAULT_POST_PROCESS_PLACEMENT,
	POST_PROCESS_PLACEMENTS,
	getBuiltinPostProcessOrder,
	getCustomPostProcessPlacementOrder,
	isPostProcessPlacement,
	type BuiltinPostProcessOrderEntry,
	type PostProcessPlacement,
} from "./ordering";
export {
	PostProcessGraphCompiler,
	getPostProcessRequirementChannels,
	hasPostProcessExecutionPasses,
	isPostProcessPassStage,
	resolvePostProcessExecutionOrder,
	type CompiledPostProcessGraph,
	type CompiledPostProcessPass,
	type PostProcessExecutionOrderContext,
	type PostProcessGraphCompileRequest,
} from "./PostProcessGraphCompiler";
export {
	PostProcessResourcePool,
	type PostProcessResourcePoolPrepareRequest,
	type PostProcessResourcePoolPrepareResult,
} from "./PostProcessResourcePool";
export {
	FAST_APPROXIMATE_ANTI_ALIASING_PASS_ID,
	FastApproximateAntiAliasingPass,
	createFXAAKernelParams,
	type FastApproximateAntiAliasingPassConfig,
	type SoftwareFXAAContext,
	type WebGPUFXAAContext,
	type WebGLFXAAContext,
} from "./passes/FastApproximateAntiAliasingPass";
export {
	DEFAULT_SSAO_OPTIONS,
	SCREEN_SPACE_AMBIENT_OCCLUSION_PASS_ID,
	ScreenSpaceAmbientOcclusionPass,
	SoftwareScreenSpaceAmbientOcclusionImplementation,
	WebGPUScreenSpaceAmbientOcclusionImplementation,
	WebGLScreenSpaceAmbientOcclusionImplementation,
	createSSAOKernelParams,
	resolveSSAODownsample,
	resolveSSAOOptions,
	type ResolvedSSAOOptions,
	type SSAOOptions,
	type ScreenSpaceAmbientOcclusionPassConfig,
	type SoftwareSSAOContext,
	type WebGPUSSAOContext,
	type WebGLSSAOContext,
} from "./passes/ScreenSpaceAmbientOcclusionPass";
export {
	DEFAULT_SSGI_OPTIONS,
	SCREEN_SPACE_GLOBAL_ILLUMINATION_PASS_ID,
	ScreenSpaceGlobalIlluminationPass,
	WebGPUScreenSpaceGlobalIlluminationImplementation,
	createSSGIKernelParams,
	resolveSSGIOptions,
	type ResolvedSSGIOptions,
	type SSGIOptions,
	type ScreenSpaceGlobalIlluminationPassConfig,
	type WebGPUSSGIContext,
} from "./passes/ScreenSpaceGlobalIlluminationPass";
export {
	DEFAULT_SSR_OPTIONS,
	SCREEN_SPACE_REFLECTIONS_PASS_ID,
	ScreenSpaceReflectionsPass,
	createSSRTraceParams,
	resolveSSRHistoryDescriptors,
	resolveSSRHistoryValid,
	resolveSSROptions,
	type ResolvedSSROptions,
	type SSROptions,
	type ScreenSpaceReflectionsPassConfig,
	type WebGPUSSRContext,
} from "./passes/ScreenSpaceReflectionsPass";
export {
	DEFAULT_SSREFRACTION_OPTIONS,
	SCREEN_SPACE_REFRACTIONS_PASS_ID,
	ScreenSpaceRefractionsPass,
	WebGPUScreenSpaceRefractionsImplementation,
	createSSRefractionTraceParams,
	resolveSSRefractionOptions,
	resolveSSRefractionTransientDescriptors,
	type ResolvedSSRefractionOptions,
	type SSRefractionOptions,
	type ScreenSpaceRefractionsPassConfig,
	type WebGPUSSRefractionContext,
} from "./passes/ScreenSpaceRefractionsPass";
export {
	DEFAULT_TAA_OPTIONS,
	TEMPORAL_ANTI_ALIASING_PASS_ID,
	TemporalAntiAliasingPass,
	resolveTAAOptions,
	type ResolvedTAAOptions,
	type TAAOptions,
	type TemporalAntiAliasingPassConfig,
} from "./passes/TemporalAntiAliasingPass";
export {
	BLOOM_PASS_ID,
	DEFAULT_BLOOM_OPTIONS,
	BloomPass,
	WebGPUBloomImplementation,
	WebGLBloomImplementation,
	type BloomOptions,
	type BloomPassConfig,
	type WebGPUBloomContext,
	type WebGLBloomContext,
} from "./passes/BloomPass";
export {
	DEFAULT_FOG_OPTIONS,
	FOG_PASS_ID,
	FogPass,
	WebGPUFogImplementation,
	WebGLFogImplementation,
	type FogOptions,
	type FogPassConfig,
	type WebGPUFogContext,
	type WebGLFogContext,
} from "./passes/FogPass";
export {
	DEFAULT_VOLUMETRIC_OPTIONS,
	VOLUMETRIC_LIGHTING_PASS_ID,
	VolumetricLightingPass,
	SoftwareVolumetricLightingImplementation,
	WebGPUVolumetricLightingImplementation,
	type SoftwareVolumetricLightingContext,
	type VolumetricOptions,
	type VolumetricLightingPassConfig,
	type WebGPUVolumetricLightingContext,
} from "./passes/VolumetricLightingPass";
export {
	DEFAULT_COLOR_FILTER_OPTIONS,
	SoftwareColorFilterImplementation,
	WebGPUColorFilterImplementation,
	WebGLColorFilterImplementation,
	ColorFilterPass,
	COLOR_FILTER_PASS_ID,
	type ColorFilterOptions,
	type ColorFilterPassConfig,
	type WebGPUColorFilterContext,
	type WebGLColorFilterContext,
} from "./passes/ColorFilterPass";
export {
	DEFAULT_DOF_OPTIONS,
	DEPTH_OF_FIELD_PASS_ID,
	DepthOfFieldPass,
	WebGPUDepthOfFieldImplementation,
	WebGLDepthOfFieldImplementation,
	type DOFOptions,
	type DepthOfFieldPassConfig,
	type WebGPUDepthOfFieldContext,
	type WebGLDepthOfFieldContext,
} from "./passes/DepthOfFieldPass";
export {
	GAMMA_PASS_ID,
	GAMMA_PASS_INCREMENTAL,
	GAMMA_PASS_ORDER,
	GammaPass,
	SoftwareGammaImplementation,
	WebGPUGammaImplementation,
	WebGLGammaImplementation,
	type WebGPUGammaContext,
} from "./passes/GammaPass";
export {
	DEFAULT_MOTION_BLUR_OPTIONS,
	MOTION_BLUR_PASS_ID,
	MotionBlurPass,
	WebGPUMotionBlurImplementation,
	WebGLMotionBlurImplementation,
	type MotionBlurOptions,
	type MotionBlurPassConfig,
	type WebGPUMotionBlurContext,
	type WebGLMotionBlurContext,
} from "./passes/MotionBlurPass";
export {
	TONE_MAPPING_PASS_ID,
	TONE_MAPPING_PASS_INCREMENTAL,
	TONE_MAPPING_PASS_ORDER,
	ToneMappingPass,
	SoftwareToneMappingImplementation,
	WebGPUToneMappingImplementation,
	WebGLToneMappingImplementation,
	type WebGPUToneMappingContext,
	type WebGLToneMappingContext,
} from "./passes/ToneMappingPass";
export {
	type SoftwareBuiltinPostProcessContext,
	type WebGLScreenPostProcessContext,
	type WebGPURuntimePostProcessContext,
	type WebGPUScreenPostProcessContext,
} from "./passes/ScreenPassShared";
export {
	PostProcessPass,
	PostProcessPassRegistry,
	PostProcessPassRegistrySnapshot,
	getEnabledCustomPostProcessPassIds,
	hasEnabledCustomPostProcessPass,
	type PostProcessPassChange,
	type PostProcessPassConfig,
	type PostProcessPassId,
	type PostProcessPassRegistryChange,
	type PostProcessPassResolveRequest,
	type PostProcessPassWarmupRequest,
	type ResolvedPostProcessPass,
} from "./PostProcessPass";
export type {
	IPostProcessExecutor,
	LogicalGBufferBridge,
	LogicalGBufferChannel,
	LogicalGBufferHandle,
	LogicalGBufferSemantic,
	PostProcessBackendKind,
	PostProcessFrameAbortRequest,
	PostProcessFrameEndRequest,
	PostProcessFrameRequest,
	PostProcessBaseResourceDescriptor,
	PostProcessHistoryDescriptor,
	PostProcessHistoryResolveRequest,
	PostProcessHistorySlot,
	PostProcessHistorySlots,
	PostProcessPassExecutionContextRequest,
	PostProcessColorFlow,
	PostProcessPassCompletion,
	PostProcessGraphHistoryUse,
	PostProcessGraphFrameBinding,
	PostProcessGraphMetadata,
	PostProcessGraphResourceUse,
	PostProcessPassImplementation,
	PostProcessPassImplementationMetadata,
	PostProcessPassRequest,
	PostProcessPassRequirements,
	PostProcessPassResult,
	PostProcessResourceMipMode,
	PostProcessResourceDescriptor,
	PostProcessResourceHandle,
	PostProcessScaledResourceDescriptor,
	PostProcessTransientDescriptor,
	PostProcessTransientSlot,
	PostProcessTransientSlots,
} from "./types";
