import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(
	path.dirname(fileURLToPath(import.meta.url)),
	".."
);
const shaderRoot = path.join(repoRoot, "src", "shaders");
const outputPath = path.join(
	shaderRoot,
	"generated",
	"embeddedShaderSources.ts"
);
const syncOutputPath = path.join(
	shaderRoot,
	"generated",
	"embeddedSyncShaderSources.ts"
);
const syncShaderPaths = new Set(["./webgpu/utility/mipmapBlit.wgsl"]);

async function collectShaderFiles(relativeRoot, extension) {
	const root = path.join(shaderRoot, relativeRoot);
	const files = [];

	async function walk(directory) {
		const entries = await readdir(directory, { withFileTypes: true });
		for (const entry of entries) {
			const fullPath = path.join(directory, entry.name);
			if (entry.isDirectory()) {
				await walk(fullPath);
				continue;
			}
			if (!entry.isFile() || !entry.name.endsWith(extension)) {
				continue;
			}
			const relativePath = path
				.relative(shaderRoot, fullPath)
				.split(path.sep)
				.join("/");
			files.push(`./${relativePath}`);
		}
	}

	await walk(root);
	return files;
}

function serializeString(value) {
	return JSON.stringify(value)
		.replaceAll("<", "\\u003c")
		.replaceAll(">", "\\u003e")
		.replaceAll("\u2028", "\\u2028")
		.replaceAll("\u2029", "\\u2029");
}

async function main() {
	const paths = [
		...(await collectShaderFiles("webgpu", ".wgsl")),
		...(await collectShaderFiles(path.join("webgl", "parts"), ".glsl")),
	].sort();

	if (paths.length === 0) {
		throw new Error("No shader source files found.");
	}

	const entries = [];
	const syncEntries = [];
	for (const shaderPath of paths) {
		const fullPath = path.join(shaderRoot, shaderPath.slice(2));
		const source = await readFile(fullPath, "utf8");
		entries.push(
			`\t${serializeString(shaderPath)}: ${serializeString(source)},`
		);
		if (syncShaderPaths.has(shaderPath)) {
			syncEntries.push(
				`\t${serializeString(shaderPath)}: ${serializeString(source)},`
			);
		}
	}

	if (syncEntries.length !== syncShaderPaths.size) {
		throw new Error("One or more synchronous shader sources were not found.");
	}

	const output = [
		"// This file is generated by scripts/generate_shader_manifest.mjs.",
		"// Do not edit by hand; update the source shader files instead.",
		"",
		"export const embeddedShaderSources: Record<string, string> = {",
		...entries,
		"};",
		"",
	].join("\n");

	await mkdir(path.dirname(outputPath), { recursive: true });
	await writeFile(outputPath, output, "utf8");
	const syncOutput = [
		"// This file is generated by scripts/generate_shader_manifest.mjs.",
		"// Do not edit by hand; update the source shader files instead.",
		"",
		"export const embeddedSyncShaderSources: Record<string, string> = {",
		...syncEntries,
		"};",
		"",
	].join("\n");
	await writeFile(syncOutputPath, syncOutput, "utf8");
	console.log(`Generated ${paths.length} embedded shader sources.`);
}

main().catch((error) => {
	console.error(error);
	process.exitCode = 1;
});
