import { WEBGPU_SCENE_SHADER_CONSTANTS } from "./parts/constants";
import { WEBGPU_SCENE_SHADER_DEFINITIONS } from "./parts/definitions";
import { WEBGPU_SCENE_SHADER_UTILS } from "./parts/utils";
import { WEBGPU_SCENE_VERTEX_STAGE } from "./parts/vertexStage";
import { WEBGPU_SCENE_FRAGMENT_PRELUDE } from "./parts/fragmentPrelude";
import { WEBGPU_SCENE_FRAGMENT_PHONG } from "./parts/fragmentPhong";
import { WEBGPU_SCENE_FRAGMENT_PBR_SETUP } from "./parts/fragmentPbrSetup";
import { WEBGPU_SCENE_FRAGMENT_PBR_DIRECTIONAL } from "./parts/fragmentPbrDirectional";
import { WEBGPU_SCENE_FRAGMENT_PBR_POINT } from "./parts/fragmentPbrPoint";
import { WEBGPU_SCENE_FRAGMENT_PBR_SPOT } from "./parts/fragmentPbrSpot";
import { WEBGPU_SCENE_FRAGMENT_PBR_AMBIENT } from "./parts/fragmentPbrAmbient";

export const WEBGPU_SCENE_SHADER = [
	WEBGPU_SCENE_SHADER_CONSTANTS,
	WEBGPU_SCENE_SHADER_DEFINITIONS,
	WEBGPU_SCENE_SHADER_UTILS,
	WEBGPU_SCENE_VERTEX_STAGE,
	WEBGPU_SCENE_FRAGMENT_PRELUDE,
	WEBGPU_SCENE_FRAGMENT_PHONG,
	WEBGPU_SCENE_FRAGMENT_PBR_SETUP,
	WEBGPU_SCENE_FRAGMENT_PBR_DIRECTIONAL,
	WEBGPU_SCENE_FRAGMENT_PBR_POINT,
	WEBGPU_SCENE_FRAGMENT_PBR_SPOT,
	WEBGPU_SCENE_FRAGMENT_PBR_AMBIENT,
].join("\n\n");
